log:
  level: debug
  disable_sentry: true

db:
  url: postgres://postgres:password@172.17.0.1:5432/containers?sslmode=disable

listener:
  addr: :8781

cop:
  disabled: true
  endpoint: "http://..."
  upstream: "http://..."
  service_name: KeyStorage
  service_port: 80
